# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check for lock file
        run: |
          if [ -f package-lock.json ]; then
            echo "Lock file exists."
          else
            echo "Error: Dependencies lock file not found."
            exit 1
          fi
      - name: Install dependencies
        run: npm ci --if-present || npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
